<div class="container-fluid pt-4 px-4">
    <?php $form->prepare(); ?>
    <?= $this->form()->openTag($form); ?>
    <?= $this->formRow($form->get('csrf')); ?>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row">
                    <hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
                        <h1 id="index" class="text-primary">Agenda toevoegen</h1>
                    </hgroup>
                </div>
            </div>
        </div>
    </div>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <!-- Agenda import form -->
                <?= $this->partial('agenda/partial/add-form.phtml', array('form' => $form)); ?>
                <!-- End agenda import form -->
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <div class="row">
                    <div class="col-sm-12 col-md-6 col-xl-6">
                        <?= $this->formRow($form->get('submit')); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
