<?php
$this->mainMenu()->setActiveItemId('agenda');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Agenda' => $this->url('beheer/agenda'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">AGENDA BEHEER</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<h2 class="col-lg-12 col-md-12 col-sm-12 text-center">
    <?= $date->format('d-m-Y'); ?>
</h2>
<div class="row">
    <div class="col-lg-1 col-md-1 col-sm-1">
        <div class="card">
            <ul class="list-group list-group-flush">
                <?php foreach ($twentyFourHours as $hour) { ?>
                    <li class="list-group-item hourItem bg-secondary"><?= $hour ?></li>
                <?php } ?>
            </ul>
        </div>
    </div>
</div>