<?php
$this->mainMenu()->setActiveItemId('agenda');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Agenda' => $this->url('beheer/agenda'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">AGENDA BEHEER</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<h2 class="col-lg-12 col-md-12 col-sm-12 text-center">
    <?= $date->format('d-m-Y'); ?>
</h2>
<div class="row">
    <div class="col-lg-2 col-md-2 col-sm-2">
        <div class="card">
            <ul class="list-group list-group-flush">
                <?php for ($i = 0; $i < 25; $i++) { ?>
                    <li class="list-group-item bg-secondary">Cras justo odio</li>
                <?php } ?>
            </ul>
        </div>
    </div>
    <div class="col-lg-10 col-md-10 col-sm-10">
        <div class="card">
            <ul class="list-group list-group-flush">
                <?php for ($i = 0; $i < 25; $i++) { ?>
                    <li class="list-group-item bg-secondary">Cras justo odio</li>
                <?php } ?>
            </ul>
        </div>
    </div>
</div>