<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row">
                    <hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
                        <h1 id="index" class="text-primary">Agenda beheer</h1>
                    </hgroup>
                </div>
                <div class="row navigation mb-3">
                    <div class="col">
                        <a
                                class="btn btn-warning btn-sm"
                                title="Previous month"
                                href="?month=<?= $navigationLinks['preMonth'] ?>&year=<?= $navigationLinks['preYear'] ?>">
                            <i class="fas fa-angle-double-left"></i>
                        </a>
                    </div>
                    <div class="col text-center">
                        <a href="<?= $this->url('beheer/agenda'); ?>" title="Vandaag" class="btn btn-warning btn-sm">Vandaag</a>
                        <div class="btn-group">
                            <button id="agendaLayout" type="button" class="btn btn-warning btn-sm dropdown-toggle"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Day
                            </button>
                            <div class="dropdown-menu bg-warning">
                                <a class="dropdown-item<?= ($layout == 'day' ? ' active' : ''); ?>" data-layout="day"
                                   href="/beheer/agenda/day">Day</a>
                                <a class="dropdown-item<?= ($layout == 'week' ? ' active' : ''); ?>" data-layout="week"
                                   href="/beheer/agenda/week">Week</a>
                                <a class="dropdown-item<?= ($layout == 'month' ? ' active' : ''); ?>"
                                   data-layout="month"
                                   href="/beheer/agenda">Month</a>
                            </div>
                        </div>
                        <input type="hidden" name="layout" value="<?= $layout ?>"/>
                    </div>
                    <div class="col text-end">
                        <a
                                class="btn btn-warning btn-sm"
                                title="Next month"
                                href="?month=<?= $navigationLinks['nextMonth'] ?>&year=<?= $navigationLinks['nextYear'] ?>">
                            <i class="fas fa-angle-double-right"></i>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 calendarColLeft">
                        <div class="table-responsive calendarContent bg-dark">
                            <table class="table borderless">
                                <tr class="orange">
                                    <th>WK</th>
                                    <?php foreach ($dayLabels as $dayLabel) { ?>
                                        <th><?= $dayLabel; ?></th>
                                    <?php } ?>
                                </tr>
                                <?php $dayCount = 1; ?>
                                <?php for ($i = 0; $i < $weeksInMonth; $i++) { ?>
                                    <?php
                                    $weekNumber = $this->agendaViewHelper()->getWeekNumber(
                                        $selectedMonthYear->format('Y'),
                                        $selectedMonthYear->format('m'),
                                        $i
                                    );
                                    ?>
                                    <tr class="white">
                                        <th>
                            <span
                                    class="weekLink"
                                    data-link="<?= $this->url('beheer/agenda', [
                                            'action' => 'week',
                                            'day' => $selectedMonthYear->format('Y') . $weekNumber
                                        ]
                                    ); ?>">
                                <?= $weekNumber; ?>
                            </span>
                                        </th>
                                        <?php
                                        //Create days in a week

                                        for ($j = 1; $j <= 7; $j++) { ?>
                                            <?php
                                            $day = null;

                                            if (($i == 0 && $j >= $firstDayOfTheMonth->format('N')) || ((int)$i > 0)) {
                                                $day = $this->agendaViewHelper()->showDay(
                                                    $selectedMonthYear->format('m'),
                                                    $selectedMonthYear->format('Y'),
                                                    $dayCount
                                                );
                                                $dayCount++;
                                            }


                                            ?>
                                            <?php if (is_object($day)) { ?>
                                                <th>
                                <span class="dateLink <?= ($day->format('Ymd') == $currentDate->format('Ymd') ? 'bg-warning text-dark' : '') ?>"
                                      data-date="<?= $day->format('d-m-Y') ?>"
                                      data-link="<?= $this->url('beheer/agenda', [
                                              'action' => 'day',
                                              'day' => $day->format('Ymd')
                                          ]
                                      ); ?>">
                                <?= $day->format('j'); ?>
                                <?= (!empty($agendaItems) && count($agendaItems[$day->format('Ymd')]??[]) > 0 ? '<span class="agendaItem">' . count($agendaItems[$day->format('Ymd')]??[]) . '</span>' : ''); ?>
                            </span>
                                                </th>
                                            <?php } else { ?>
                                                <th>&nbsp;</th>
                                            <?php } ?>
                                            <?php
                                        }
                                        ?>
                                    </tr>
                                <?php } ?>
                            </table>
                        </div>
                    </div>
                    <div class="col-md-4 calendarColRight">
                        <div class="dateContent">
                            <div id="date" class="text-right"><?= $currentDate->format('j'); ?></div>
                            <div id="day"
                                 class="text-right">
                                <?= $this->agendaViewHelper()->getDayLabels('nl', 'long')[$currentDate->format('N')]; ?>
                            </div>
                            <div id="month"
                                 class="text-right">
                                <?= $this->agendaViewHelper()->getMonthLabels('nl', $currentDate->format('n')); ?>
                                /<?= $currentDate->format('Y'); ?>
                            </div>
                            <div>
                                <table class="table table-borderless" id="agendaItemsForDay">
                                    <tbody>
                                    <?php foreach ($agendaItemsForCurrentDate as $agendaItem) { ?>
                                        <tr>
                                            <td style="width:60%; font-family:arial"><?= $this->agendaViewHelper()->shortenTitle($agendaItem->getTitle()); ?></td>
                                            <td style="width:40%; font-family:arial"
                                                class="text-right"><?= $agendaItem->getStartTime()->format('H:i:s'); ?>
                                                - <?= $agendaItem->getEndTime()->format('H:i:s'); ?></td>
                                        </tr>

                                    <?php } ?>
                                    </tbody>
                                </table>
                            </div>

                            <!-- Button trigger add agenda item modal -->
                            <button type="button" id="addAgendaItem" class="btn btn-warning addAgendaItemButton" data-bs-toggle="modal" data-bs-target="#addingAgendaItem">
                                <i class="fas fa-plus-circle"></i>
                            </button>
                        </div>

                    </div>
                </div>

                <!-- Add agenda item modal -->
                <div class="modal fade" id="addingAgendaItem" tabindex="-1" aria-labelledby="addingAgendaItemModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <?php
                            $form->setAttribute('novalidate', 'novalidate');
                            $form->prepare();
                            ?>
                            <?= $this->form()->openTag($form); ?>
                            <div class="modal-header">
                                <h2 class="modal-title fs-5 text-primary" id="addingAgendaItemModalLabel">Add agenda item</h2>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <!-- Agenda item form -->
                                <?= $this->partial('agenda/partial/form.phtml', array('form' => $form)); ?>
                            </div>
                            <div class="modal-footer mt-4 pb-4">
                                <button id="submitAgendaItem" type="submit" class="btn btn-warning">
                                    <i class="fas fa-plus-circle"></i>
                                </button>
                                <button type="button" id="closeAddAgendaItem" class="btn btn-warning" data-bs-dismiss="modal"><i class="fas fa-times-circle"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>