<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Agenda's</h2>
                </div>
                <form name="searchEvents" method="post"
                      action="<?php echo $this->url('beheer/agenda',  ['action' => 'index']); ?>">
                    <div class="row g-4">
                        <div class="col-sm-6 col-md-6 col-xl-6">
                            <a class="btn btn-primary" href="<?= $this->url('beheer/agenda', ['action' => 'add']); ?>">
                                <i class="fas fa-plus-square"></i> New Agenda
                            </a>
                            <a class="btn btn-primary"
                               href="<?= $this->url('beheer/agenda', ['action' => 'archive']) ?>">
                                <i class="fas fa-archive"></i> Archief
                            </a>
                        </div>
                        <div class="col-sm-4 col-md-4 col-xl-4 text-end">
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                        <div class="col-sm-2 col-md-2 col-xl-2">
                            <input class="form-control" name="search" value="<?php echo $searchString; ?>"
                                   type="search"
                                   placeholder="Search" aria-label="Search">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                    <tr>
                        <th>Titel</th>
                        <th>Datum aangemaakt</th>
                        <th>Datum gewijzigd</th>
                        <th class="text-center"><i class="fas fa-cogs"></i></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (count($agendas) > 0) { ?>
                        <?php foreach ($agendas AS $agenda) { ?>
                            <tr>
                                <td><?php echo $agenda->getTitle(); ?></td>
                                <td>
                                    <?php echo(is_object($agenda->getDateCreated()) ? $agenda->getDateCreated()->format('d-m-Y H:m:s') : ''); ?>
                                </td>
                                <td>
                                    <?php echo(is_object($agenda->getDateChanged()) ? $agenda->getDateChanged()->format('d-m-Y H:m:s') : ''); ?>
                                </td>
                                <td class="text-center">
                                    &nbsp;
                                    <a class="btn btn-sm btn-primary" href="<?= $this->url('beheer/agenda', ['action' => 'detail', 'day' => $agenda->getId()]); ?>">
                                        <i class="fas fa-list-alt"></i>
                                    </a>
                                    <a class="btn btn-sm btn-primary" href="<?= $this->url('beheer/agenda', ['action' => 'edit', 'day' => $agenda->getId()]); ?>">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a class="btn btn-sm btn-primary" href="<?= $this->url('beheer/agenda', ['action' => 'archief', 'day' => $agenda->getId()]); ?>">
                                        <i class="fas fa-archive"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                    <tr>
                        <td class="text-center" colspan="4">Geen agenda's aanwezig!</td>
                    </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <?php if (count($agendas) > 0) { ?>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  mt-4 p-4">
                <?= $this->paginationControl($agendas,
                    'Sliding',
                    'layout/paginator',
                    array('route' => 'beheer/blog')) ?>
            </div>
        </div>
    </div>
    <?php } ?>
</div>
